---
title: "US Population: 1790-1840"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      fig.width = 10, fig.height = 10)
library(tidyverse)
library(stringr)
#
options(scipen = 999)
#
census_1790_1840 <- read_csv("/Users/bnbh_imac/Desktop/test_project/Input/C_1790_1840.csv")
#changes changes changes
state_fips_to_name <- readxl::read_xlsx("/Users/bnbh_imac/Desktop/test_project/Input/state_fips_to_name.xlsx")
#--------
tot_pop <- census_1790_1840 %>%
  group_by(year) %>%
  summarise("Free" = sum(cntypopf, na.rm = T),
            "Not Free" = sum(cntypops, na.rm = T),
            "Total" = `Free` + `Not Free`)
#
region_label <- census_1790_1840 %>%
  select(region, statefip) %>%
  distinct() %>%
  arrange(region) %>%
  left_join(., state_fips_to_name, by = c("statefip" = "st")) %>%
  group_by(region) %>%
  summarise(label = paste0(stusps, collapse = ", "))
```

# National  

```{r}
tot_p1 <- tot_pop %>%
  pivot_longer(-year) %>%
  ggplot(data = .,
       aes(x = year, y = value, group = name, color = name)) +
  geom_line() + geom_point() +
  scale_y_continuous(labels = scales::comma_format()) +
  labs(x = "Year", y = "Population") +
  theme(legend.title = element_blank())
#
tot_p2 <- tot_pop %>%
  mutate("Free" = `Free` / `Total`,
         "Not Free" = `Not Free` / `Total`) %>%
  select(year, `Free`, `Not Free`) %>%
  pivot_longer(-year) %>%
  ggplot(data = .,
         aes(x = year, y = value, fill = name)) +
  geom_col() +
  ggsci::scale_fill_aaas() +
  labs(y = "Proportion", x = "Year") +
  scale_y_continuous(labels = scales::percent_format()) +
  theme(legend.title = element_blank(),
        axis.title.y = element_blank())
#
gridExtra::grid.arrange(tot_p1, tot_p2, nrow = 1)
```

# By Census Region  

```{r}
region <- census_1790_1840 %>%
  group_by(year, region) %>%
  summarise("Free" = sum(cntypopf, na.rm = T),
            "Not Free" = sum(cntypops, na.rm = T),
            "Total" = `Free` + `Not Free`) %>%
  left_join(., region_label) %>%
  select(-region) %>%
  pivot_longer(-c(year, label)) %>%
  na_if(., 0)

region_p1 <- ggplot(data = region,
         aes(x = year, y = value, group = name, color = name)) +
  geom_line() + geom_point() +
  scale_y_continuous(labels = scales::comma_format()) +
  facet_wrap(~label) +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 0)) +
  labs(x = "Year",
       y = "Population") +
  theme(legend.title = element_blank())
#
region_p2 <- census_1790_1840 %>%
  group_by(year, region) %>%
  summarise("Free" = sum(cntypopf, na.rm = T),
            "Not Free" = sum(cntypops, na.rm = T),
            total = `Free` + `Not Free`) %>%
  left_join(., region_label) %>%
  select(-region) %>%
  mutate("Free" = `Free` / total,
         "Not Free" = `Not Free` / total) %>%
  select(-total) %>%
  pivot_longer(-c(year, label)) %>%
  ggplot(data = .,
         aes(x = year, y = value, fill = name)) +
  geom_col() +
  ggsci::scale_fill_aaas() +
  labs(y = "Proportion", x = "Year") +
  scale_y_continuous(labels = scales::percent_format()) +
  theme(legend.title = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 0)) +
  facet_wrap(~label)
#
gridExtra::grid.arrange(region_p1, region_p2, nrow = 1)
```


# By State  


```{r}
state_p1 <- census_1790_1840 %>%
  group_by(year, statefip) %>%
  summarise(`Free` = sum(cntypopf, na.rm = T),
            `Not Free` = sum(cntypops, na.rm = T),
            `Total` = `Free` + `Not Free`) %>%
  left_join(state_fips_to_name, by = c("statefip" = "st")) %>%
  select(-c(statefip, stusps)) %>%
  pivot_longer(-c(year, stname)) %>%
  na_if(., 0) %>%
  ggplot(data = .,
         aes(x = year, y = value, color = name, group = name)) +
  geom_line() + geom_point(size = 0.5) +
  facet_wrap(~stname) +
  scale_y_continuous(labels = scales::comma_format()) +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 0)) +
  labs(x = "Year",
       y = "Population") +
  theme(legend.title = element_blank())
#
state_p2 <- census_1790_1840 %>%
  group_by(year, statefip) %>%
  summarise(free_pop = sum(cntypopf, na.rm = T),
            notFree_pop = sum(cntypops, na.rm = T),
            `Free` = free_pop / (free_pop + notFree_pop),
            `Not Free` = notFree_pop / (free_pop + notFree_pop)) %>%
  left_join(state_fips_to_name, by = c("statefip" = "st")) %>%
  select(year, stname, `Free`, `Not Free`) %>%
  pivot_longer(-c(year, stname)) %>%
  ggplot(data = .,
         aes(x = year, y = value, fill = name)) +
  geom_col() +
  ggsci::scale_fill_aaas() +
  labs(y = "Proportion", x = "Year") +
  scale_y_continuous(labels = scales::percent_format()) +
  theme(legend.title = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 0)) +
  facet_wrap(~stname)
#==
gridExtra::grid.arrange(state_p1, state_p2, nrow = 1)
```
